### PR TITLE
chore(sidekick): prepare for manifest v3 version

### PR DESCRIPTION
**Pull request by rofe**
https://sidekick-mv3--fedpub--adobe.hlx.page/creativecloud/photography/hub/guides/guide-to-aperture-vs-iris

To try it out, create a local checkout of the [`helix-sidekick-extension`](https://github.com/adobe/helix-sidekick-extension) repo, switch to the `mv3` branch and follow these instructions:
https://github.com/adobe/helix-sidekick-extension#local-testing

### CODE REVIEW

**Review by amauch-adobe — CHANGES_REQUESTED** [review]
@rofe, I followed your instructions for testing this out, meaning I installed the mv3 version of the helix sidekick by using the branch specified.  I then added the FedPup site to the helix sidekick extension and then went to the URL you have in the summary.  When I did that I no longer could see the different plugin buttons specific to the FedPup config.json in your PR, meaning on the preview view the "LinkChecker" button was no longer there and then the "Tagger" button also was gone when in edit mode/view.  I noticed those were specific config options according to the JSON so I was wondering why they aren't showing up for the helix sidekick mv3 version?

Other than that concern, everything else looked good.

**Comment by rofe** [comment]
@amauch-adobe when testing this using the sidekick extension from your local checkout of the `mv3` branch, do you see a request to `/tools/sidekick/config.json` being made in the browser console?

**Comment by rofe** [comment]
Sorry, this can of course only be tested on the sidekick-mv3 branch of this project, so you would need to set your sidekick to use https://github.com/adobe/fedpub/tree/sidekick-mv3 as GitHub URL and then come here:

https://sidekick-mv3--fedpub--adobe.hlx.page/creativecloud/photography/hub/guides/guide-to-aperture-vs-iris

**Comment by rofe** [comment]
@amauch-adobe have you been able to test this with the updated instructions above?

**Review by amauch-adobe — CHANGES_REQUESTED** [review]
@rofe , I went back and relooked at things according to your instructions above and I indeed see the config.json file coming from the feature branch sidekick-mv3 /tools/sidekick/config.json just fine.  I did get an error though with requesting the plugins.js.  I get a failed request for that file both in the console and in the network tab.  This only happens when in Preview mode though.  In production mode when I clicked Linkchecker nothing happens, I don't even see any errors in the console or network tab when I clicked the Linkchecker button.  When I compared the behavior with the current version of the sidekick out in public consumption the Linkchecker button worked only on Production mode and highlighted links in a box.  So I assumed that should be the same behavior for this feature branch.
I also only see the Tagger tab when in "edit" mode (meaning viewing the word document in SharePoint).  Based on the config.json I should see translate as well, I believe.  
Screen Shot 2022-08-30 at 6 55 21 PM
Screen Shot 2022-08-30 at 6 55 10 PM

**Comment by rofe** [comment]
Good catch, @amauch-adobe. I think FedPub is a special case in the sense that we don't own the root in prod - so in order to be able to load a `plugins.js` on prod, it needs to move to the `hub` folder.

I can update the PR, if you don't beat me to it 😄

**Comment by rofe** [comment]
@amauch-adobe I moved the `plugins.js` to `hub/scripts` now, where it can also be loaded in prod.

> I did get an error though with requesting the plugins.js. I get a failed request for that file both in the console and in the network tab. This only happens when in Preview mode though.

I couldn't (can no longer?) reproduce this in preview. Make sure your sidekick config is pointing to the `sidekick-mv3` ref.

>  In production mode when I clicked Linkchecker nothing happens, I don't even see any errors in the console or network tab when I clicked the Linkchecker button. 

This behavior can unfortunately only be tested in actual production, when the `plugins.js` gets loaded. That will listen for the event from the sidekick and invoke the linkchecker code.

The new `plugins.js` path will ensure it will be delivered through Akamai.

> When I compared the behavior with the current version of the sidekick out in public consumption the Linkchecker button worked only on Production mode and highlighted links in a box.

We'll have to merge this PR to `main` to see it in action. On a side note: the linkchecker as it's implemented today won't work anywhere else than production due to CORS limitations (fetching `adobe.com` URLs from `*.hlx.page` is forbidden), so I'm wondering if we should limit the plugin to the `prod` environment in `config.json`... alternatively, the code could be refactored to fetch relative paths, but I'm not sure if that would be in line with its original purpose.

> I also only see the Tagger tab when in "edit" mode (meaning viewing the word document in SharePoint). Based on the config.json I should see translate as well, I believe.

Only when opening Excel files. Try https://sidekick-mv3--fedpub--adobe.hlx.page/taxonomy.json

**Review by amauch-adobe — APPROVED** [review]
Approved, the moving of the plugin.js file to hub/scripts resolved the request error.  Also, thanks for the clarification for the LinkChecker as well as the Translate button option.

QA validated and approved.

**Pull request merged**
